version: '3'
services:
  backend:
    image: recast321/proj-backend 
    ports:
      - "8000:8000"
    env_file: .env  # Make sure your .env file is in the same directory as docker-compose.yml

  frontend:
    image: recast321/proj-frontend  
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file: .env  # Make sure your .env file is in the same directory as docker-compose.yml
